setting page
ATOZ-TEAM/payplo-front pull request #4
Opened 2023-10-05 09:43 UTC by i-jinkyung

## :: 최근 작업 주제
- [x] 레이아웃 추가
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정
<br />

## :: 구현 목표
1. Setting 페이지 구현하기
<br />

## :: 구현 사항 설명

2023-10-06 13:32 UTC, yhk1038 commented
하단바에서 세팅 메뉴 클릭시 세팅 페이지로 연결되지 않고, 아직 "준비중입니다" 얼럿이 뜨고 있어요.
수정 필요해보입니다!

2023-10-06 14:59 UTC, yhk1038 requested changes
속도에 엄청 놀라서 코드도 실행해봤는데 생각보다 훨씬 적응 잘 하신듯 해서 두번 놀랐습니다!
크게 어긋남 없이 만들어주셔서 큰 수정은 없는데, 코드리뷰 차원에서 자잘한 수정 요청들 남겨 봅니다!

2023-10-06 14:59 UTC, yhk1038 commented on src/components/pages/v3/V3OrgSettingsPage/mobile/InformationPanel.tsx
> +                    <MobileInfoListItem
@i-jinkyung 
클릭할 수 있는 컴포넌트라면,
클릭할 수 있는 컴포넌트라는 사실을 사용자에게 적극적으로 알려야 합니다.
이를 위해 아래 패턴을 챙겨주세요 :)

1. hover style 지정 (마우스를 올리면, 컴포넌트가 클릭되는 범위와 준비상태를 적절하게 표현해야 합니다. 예를들어 하이퍼링크의 경우 마우스를 올리면 밑줄이 나오고 조금 더 진한 색체로 표기되는 등의 효과를 말합니다.)
2. cursor-pointer css 클래스 추가 (마우스를 올리면 손가락 모양으로 포인터가 변해야 합니다.)
   - 이는 위 1번의 hover 스타일 적용의 최소 적용이 될 수 있습니다.
   - 예를들어 InfoListItem 의 경우 hover 스타일은 스코디 앱내에서 보편적으로 cursor-pointer만 적용하고 있습니다.


이건 이하 다른 링크들에도 마찬가지 입니다!

2023-10-06 14:59 UTC, yhk1038 commented on src/components/pages/v3/V3OrgSettingsPage/mobile/OrgProfilePanel.tsx
> +interface OrganizationProps {
@i-jinkyung 아래에 등장할 `OrgProfilePanel` 만을 위한 속성 인터페이스 이므로,
`OrgProfilePanelProps` 로 정정해주세요.

컴포넌트 속성 인터페이스는 재사용에 관한 별다른 특별한 이유가 없다면,
"컴포넌트명" + "Props" 라고 작성을 통일하면 좋을 것 같아요!

죽 보니 다른 컴포넌트들에도 비슷한 이슈가 있던데,
같이 함께 챙겨주세요!

2023-10-06 14:59 UTC, yhk1038 commented on src/components/pages/v3/V3OrgSettingsPage/index.tsx
> +                {isOrganization ? <OrgProfilePanel isOrganization={isOrganization} /> : <UserProfilePanel />}
@i-jinkyung 
`OrgProfilePanel` 은 isOrganization 가 반드시 true 일 때만 출력되는것으로 보입니다.
`OrgProfilePanel` 에 isOrganization 속성을 굳이 넣지 않아도 될 것 같은데, 괜찮다면 빼는게 어떨까요?

2023-10-06 14:59 UTC, yhk1038 commented on src/components/pages/v3/V3OrgSettingsPage/mobile/SettingPanel.tsx
> +    setIsOrganization: React.Dispatch<React.SetStateAction<boolean>>;
@i-jinkyung 
`React.Dispatch`, `React.SetStateAction` 여시거 React 네임스페이스는 생략해주세요.

그러면 import 구문은 이렇게 되고
`import React, {memo, Dispatch, SetStateAction} from 'react';`

타입선언은 이렇게 바뀌어야 합니다.
`Dispatch<SetStateAction<boolean>>`

2023-10-06 14:59 UTC, yhk1038 commented on src/components/pages/v3/V3OrgSettingsPage/mobile/OrgProfilePanel.tsx
> +                    <Modal type="info" isOpen={isModalOpen} title="조직명 변경">
@i-jinkyung 
이거 모달 끌 수 있는 방법이 없어요 ㅠㅠ

`useModal` 훅이 있는데, 이 훅을 사용해보시는걸 추천드립니다!

2023-10-06 15:46 UTC, yhk1038 commented on src/components/pages/v3/V3OrgSettingsPage/mobile/OrgProfilePanel.tsx
> +    const CurrentOrgName = currentOrg?.name;
@i-jinkyung `class` 나 `전역 상수`가 아닌 변수명은 소문자로 시작해주세요.

클래스 이름은 파스칼케이스, 일반 변수는 카멜케이스를 원칙으로 합니다 :)

참고로 이외에도 전역상수인 경우에는 `export const CURRENT_ORG_NAME` 와 같이 전체 대문자인 UppperCase 를 적용한답니다 ㅎㅎ

2023-10-07 04:54 UTC, newbieJanghan commented
이것이 코드리뷰군요

2023-10-12 07:55 UTC, merged

2023-10-12 12:27 UTC, yhk1038 commented
@i-jinkyung 근데 이거 위에 문서랑 리뷰 리졸브들좀 해주세요 ㅋㅋㅋ